/* tslint:disable */
/* eslint-disable */
/**
 * Todo api swagger
 * Testing todo swagger API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthLoginPostRequest
 */
export interface ApiAuthLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAuthLoginPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthLoginPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiAuthLoginPostRequest interface.
 */
export function instanceOfApiAuthLoginPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ApiAuthLoginPostRequestFromJSON(json: any): ApiAuthLoginPostRequest {
    return ApiAuthLoginPostRequestFromJSONTyped(json, false);
}

export function ApiAuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthLoginPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiAuthLoginPostRequestToJSON(value?: ApiAuthLoginPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

