/* tslint:disable */
/* eslint-disable */
/**
 * Todo api swagger
 * Testing todo swagger API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthRegisterPostRequest
 */
export interface ApiAuthRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAuthRegisterPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthRegisterPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthRegisterPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthRegisterPostRequest
     */
    confirmPassword: string;
}

/**
 * Check if a given object implements the ApiAuthRegisterPostRequest interface.
 */
export function instanceOfApiAuthRegisterPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;

    return isInstance;
}

export function ApiAuthRegisterPostRequestFromJSON(json: any): ApiAuthRegisterPostRequest {
    return ApiAuthRegisterPostRequestFromJSONTyped(json, false);
}

export function ApiAuthRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthRegisterPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'username': json['username'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function ApiAuthRegisterPostRequestToJSON(value?: ApiAuthRegisterPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'username': value.username,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

