/* tslint:disable */
/* eslint-disable */
/**
 * Todo api swagger
 * Testing todo swagger API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiGroupGroupIdPutRequest
 */
export interface ApiGroupGroupIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiGroupGroupIdPutRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ApiGroupGroupIdPutRequest interface.
 */
export function instanceOfApiGroupGroupIdPutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ApiGroupGroupIdPutRequestFromJSON(json: any): ApiGroupGroupIdPutRequest {
    return ApiGroupGroupIdPutRequestFromJSONTyped(json, false);
}

export function ApiGroupGroupIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGroupGroupIdPutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ApiGroupGroupIdPutRequestToJSON(value?: ApiGroupGroupIdPutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

