/* tslint:disable */
/* eslint-disable */
/**
 * Todo api swagger
 * Testing todo swagger API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTodoPostPostRequest
 */
export interface ApiTodoPostPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiTodoPostPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTodoPostPostRequest
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTodoPostPostRequest
     */
    statusId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiTodoPostPostRequest
     */
    groupId: number;
}

/**
 * Check if a given object implements the ApiTodoPostPostRequest interface.
 */
export function instanceOfApiTodoPostPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "statusId" in value;
    isInstance = isInstance && "groupId" in value;

    return isInstance;
}

export function ApiTodoPostPostRequestFromJSON(json: any): ApiTodoPostPostRequest {
    return ApiTodoPostPostRequestFromJSONTyped(json, false);
}

export function ApiTodoPostPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTodoPostPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'statusId': json['status_id'],
        'groupId': json['group_id'],
    };
}

export function ApiTodoPostPostRequestToJSON(value?: ApiTodoPostPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
        'status_id': value.statusId,
        'group_id': value.groupId,
    };
}

